# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
host: localhost

title: Frontier Realty
email: info@frontierRealty.com
description: 'Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.'

carousel:
  - pic: 2
  - pic: 3
  - pic: 4
  - pic: 5
  - pic: 6

#Services provided by the Office:
services:
  - type: Buy
    description: something something fake fake fake with a load of fake stuff for placeholder content.
    icon: home

  - type: Sell
    description: something something fake fake fake with a load of fake stuff for placeholder content.
    icon: briefcase

  - type: Loan
    description: something something fake fake fake with a load of fake stuff for placeholder content.
    icon: university

# Team names, titles and social links
people:
  - name: Kay Garland
    pic: 1
    position: Lead Designer
    social:
      - title: facebook
        url: #
      - title: linkedin
        url: #
  - name: Kay Garland
    pic: 1
    position: Lead Designer
    social:
      - title: facebook
        url: #
      - title: linkedin
        url: #

  - name: Kay Garland
    pic: 1
    position: Lead Designer
    social:
      - title: facebook
        url: #
      - title: linkedin
        url: #

  - name: Kay Garland
    pic: 1
    position: Lead Designer
    social:
      - title: facebook
        url: #
      - title: linkedin
        url: #

  - name: Larry Parker
    pic: 2
    position: Lead Marketer
    social:
      - title: facebook
        url: #
      - title: linkedin
        url: #

  - name: Diana Petersen
    pic: 3
    position: Lead Developer
    social:
      - title: facebook
        url: #
      - title: google-plus
        url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url:
  - title: linkedin
    url:

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
