# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
host: localhost

title: Frontier Realty
email:
  - emailicon: info@frontierRealty.com
description: 'Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.'

carousel:
  - pic: 2
  - pic: 3
  - pic: 4
  - pic: 5
  - pic: 6

#Services provided by the Office:
services:
  - type: Buy
    description: something something fake fake fake with a load of fake stuff for placeholder content. something something fake fake fake with a load of fake stuff for placeholder content.
    icon: home

  - type: Sell
    description: something something fake fake fake with a load of fake stuff for placeholder content. something something fake fake fake with a load of fake stuff for placeholder content.
    icon: briefcase

  - type: Loan
    description: something something fake fake fake with a load of fake stuff for placeholder content. something something fake fake fake with a load of fake stuff for placeholder content.
    icon: university

#Real Estate Education
education:
  - program: How to Buy
    description: something something fake fake fake with a load of fake stuff for placeholder content.I actually want to write a lot of these things and information to make sure that I can get the correct information.
    icon: home

  - program: How to Sell
    description: something something fake fake fake with a load of fake stuff for placeholder content.I actually want to write a lot of these things and information to make sure that I can get the correct information.
    icon: home

  - program: How to Invest
    description: something something fake fake fake with a load of fake stuff for placeholder content.I actually want to write a lot of these things and information to make sure that I can get the correct information.
    icon: home

  # - program: How to Real Estate
  #   description: something something fake fake fake with a load of fake stuff for placeholder content.
  #   icon: home

# Team names, description, titles and social links
team:
  - description: something something fake fake fake with a load of fake stuff for placeholder content.

people:
  - name: Jack Luan Tran
    pic: 1
    position: Broker/C.E.O
    social:
      - title: facebook
        url: #
      - title: linkedin
        url: #
    contacts:
      - phoneicon: phone
      - phone: ': 714-360-5098'
      # - email:
      # - emailicon:
    bre: 01852802

  - name: Richard Le
    pic: 1
    position: Realtor
    social:
      - title: facebook
        url: #
      - title: linkedin
        url: #
    contacts:
      - phoneicon: phone
      - phone: ': 714-468-7363'
      # - email:
      # - emailicon:
    bre: 02044899

  - name: Carol Chau
    pic: 1
    position: Realtor
    social:
      - title: facebook
        url: #
      - title: linkedin
        url: #
    contacts:
      - phoneicon: phone
      - phone: ': 714-858-4450'
      # - email:
      # - emailicon:
    bre: 02010924

  - name: Trung Do
    pic: 1
    position: Realtor
    social:
      - title: facebook
        url: #
      - title: linkedin
        url: #
    contacts:
      - phoneicon: phone
      - phone: ': 714-725-1615'
      # - email:
      # - emailicon:
    bre: 02052647

  - name: Molly Dinh
    pic: 2
    position: Realtor
    social:
      - title: facebook
        url: #
      - title: linkedin
        url: #
    contacts:
      - phoneicon: phone
      - phone: ': 949-939-4470'
      # - email:
      # - emailicon:
    bre: 02047175

  - name: Jason Tang
    pic: 3
    position: Realtor
    social:
      - title: facebook
        url: #
      - title: linkedin
        url: #
    contacts:
      - phoneicon: phone
      - phone: ': 949-690-6229'
      # - email:
      # - emailicon:
    bre: 01932186

  - name: Linda Le
    pic: 3
    position: Realtor
    social:
      - title: facebook
        url: #
      - title: linkedin
        url: #
    contacts:
      - phoneicon: phone
      - phone: ': 213-279-6789'
      # - email:
      # - emailicon:
    bre: 01809137

  - name: Hiep Do
    pic: 3
    position: Realtor, Architecture
    social:
      - title: facebook
        url: #
      - title: linkedin
        url: #
    contacts:
      - phoneicon: phone
      - phone: ': 714-589-4007'
      # - email:
      # - emailicon:
    bre: 02049706

  - name: Michael Lee
    pic: 3
    position: Realtor
    social:
      - title: facebook
        url: #
      - title: linkedin
        url: #
    contacts:
      - phoneicon: phone
      - phone: ': 714-351-2120'
      # - email:
      # - emailicon:
    bre: 01997760

  - name: Michael Lee
    pic: 3
    position: Realtor
    social:
      - title: facebook
        url: #
      - title: linkedin
        url: #
    contacts:
      - phoneicon: phone
      - phone: ': 714-351-2120'
      # - email:
      # - emailicon:
    bre: 01997760

  - name: Michael Lee
    pic: 3
    position: Realtor
    social:
      - title: facebook
        url: #
      - title: linkedin
        url: #
    contacts:
      - phoneicon: phone
      - phone: ': 714-351-2120'
      # - email:
      # - emailicon:
    bre: 01997760

  - name: Michael Lee
    pic: 3
    position: Realtor
    social:
      - title: facebook
        url: #
      - title: linkedin
        url: #
    contacts:
      - phoneicon: phone
      - phone: ': 714-351-2120'
      # - email:
      # - emailicon:
    bre: 01997760

  - name: Michael Lee
    pic: 3
    position: Realtor
    social:
      - title: facebook
        url: #
      - title: linkedin
        url: #
    contacts:
      - phoneicon: phone
      - phone: ': 714-351-2120'
      # - email:
      # - emailicon:
    bre: 01997760

  - name: Michael Lee
    pic: 3
    position: Realtor
    social:
      - title: facebook
        url: #
      - title: linkedin
        url: #
    contacts:
      - phoneicon: phone
      - phone: ': 714-351-2120'
      # - email:
      # - emailicon:
    bre: 01997760

# Social networks usernames (many more available: linkedin, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url:
  - title: linkedin
    url:

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
